### PR TITLE
Modernize Qt setup with AUTOUIC and Qt components

### PR DESCRIPTION
**Pull request by forderud**
Changes:
* Start using the `find_package` COMPONENT feature. 
* Enable automatic `UIC` calls.
* Remove unused `Qt5::WinMain` dependency

This PR fixes my build problems with Qt 5.12 on non-Windows platforms.

### CODE REVIEW

**Comment by forderud** [comment]
@jasondegraw This project was the first hit I got when searching for a Qt CMake example. I therefore want to update it, so that it builds out-of-the-box also with the latest version of Qt & CMake.

Can you please review this PR?

**Comment by jasondegraw** [comment]
Sure, I can take a look this coming weekend

**Comment by forderud** [comment]
Gentle reminder.

**Comment by jasondegraw** [comment]
Looks good, will merge here momentarily.

**Pull request merged**
